services:
  - type: web
    name: gamax-cm-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/products
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_BASE_URL
        value: https://shop.gamax-cm.fr
      - key: PORT
        value: 3000
